/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["api_schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_categories_list"];
        put?: never;
        post: operations["admin_categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_categories_retrieve"];
        put?: never;
        post?: never;
        delete: operations["admin_categories_destroy"];
        options?: never;
        head?: never;
        patch: operations["admin_categories_partial_update"];
        trace?: never;
    };
    "/api/v1/admin/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_products_list"];
        put?: never;
        post: operations["admin_products_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_products_retrieve"];
        put?: never;
        post?: never;
        delete: operations["admin_products_destroy"];
        options?: never;
        head?: never;
        patch: operations["admin_products_partial_update"];
        trace?: never;
    };
    "/api/v1/admin/products/{product_id}/images/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach a photo to a product
         * @description Multipart upload; the model converts the original to WebP at three widths.
         */
        post: operations["admin_products_images_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products/{product_id}/images/{image_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a photo and its derivatives */
        delete: operations["admin_products_images_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counters for the admin dashboard */
        get: operations["admin_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tables/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_tables_list"];
        put?: never;
        post: operations["admin_tables_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tables/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_tables_retrieve"];
        put?: never;
        post?: never;
        delete: operations["admin_tables_destroy"];
        options?: never;
        head?: never;
        patch: operations["admin_tables_partial_update"];
        trace?: never;
    };
    "/api/v1/admin/tables/{id}/qr.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One table's QR code as SVG */
        get: operations["admin_tables_qr.svg_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tables/qr-sheet.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Printable sheet of every active table's QR code */
        get: operations["admin_tables_qr_sheet.pdf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The authenticated account
         * @description `GET /auth/me/` — the object is the requesting user, so there is no lookup.
         */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a token pair
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The entire menu in one response
         * @description `GET /menu/` — cached per language for five minutes, dropped on any menu write.
         */
        get: operations["menu_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated product list */
        get: operations["products_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One product with all of its photos */
        get: operations["products_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tables/{token}/scan/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a QR scan and resolve the table number
         * @description `POST /tables/{token}/scan/`.
         *
         *     An unknown *or* inactive token is a 404 with the same body, so a retired token
         *     cannot be told apart from a fabricated one.
         */
        post: operations["tables_scan_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A section or subsection with all of its names. */
        AdminCategory: {
            readonly id: number;
            parent?: number | null;
            slug?: string;
            order?: number;
            is_active?: boolean;
            translations: components["schemas"]["CategoryTranslation"][];
            readonly missing_translations: string[];
            readonly product_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description A section or subsection with all of its names. */
        AdminCategoryRequest: {
            parent?: number | null;
            slug?: string;
            order?: number;
            is_active?: boolean;
            translations: components["schemas"]["CategoryTranslationRequest"][];
        };
        /** @description Full product record: every translation, the gaps, and the stored photos. */
        AdminProduct: {
            readonly id: number;
            category: number;
            slug?: string;
            /** @description Price in UZS, whole units only. */
            price: number;
            is_available?: boolean;
            order?: number;
            translations: components["schemas"]["ProductTranslation"][];
            readonly missing_translations: string[];
            readonly images: components["schemas"]["AdminProductImage"][];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description A stored photo with its derivative URLs, as the admin UI lists them. */
        AdminProductImage: {
            readonly id: number;
            alt?: string;
            order?: number;
            is_primary?: boolean;
            readonly width: number;
            readonly height: number;
            readonly srcset: {
                [key: string]: string;
            };
        };
        /** @description A stored photo with its derivative URLs, as the admin UI lists them. */
        AdminProductImageRequest: {
            alt?: string;
            order?: number;
            is_primary?: boolean;
        };
        /** @description Full product record: every translation, the gaps, and the stored photos. */
        AdminProductRequest: {
            category: number;
            slug?: string;
            /** @description Price in UZS, whole units only. */
            price: number;
            is_available?: boolean;
            order?: number;
            translations: components["schemas"]["ProductTranslationRequest"][];
        };
        /** @description A table as the admin UI edits it, plus the URL its QR code resolves to. */
        AdminTable: {
            readonly id: number;
            number: number;
            /** Format: uuid */
            readonly token: string;
            label?: string;
            is_active?: boolean;
            readonly scan_url: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description A table as the admin UI edits it, plus the URL its QR code resolves to. */
        AdminTableRequest: {
            number: number;
            label?: string;
            is_active?: boolean;
        };
        CategoryTranslation: {
            language: components["schemas"]["LanguageEnum"];
            name: string;
        };
        CategoryTranslationRequest: {
            language: components["schemas"]["LanguageEnum"];
            name: string;
        };
        /** @description The authenticated account, as the Next.js server needs it for its session. */
        CurrentUser: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            readonly username: string;
            readonly role: components["schemas"]["RoleEnum"];
        };
        /** @description The single error envelope produced by `apps.common.exceptions`. */
        Error: {
            detail: string;
            code: string;
            /** @description Per-field messages; empty for non-validation failures. */
            field_errors: {
                [key: string]: string[];
            };
        };
        /** @description A product photo and its WebP derivatives, identical everywhere it appears. */
        Image: {
            alt: string;
            width: number;
            height: number;
            /**
             * Format: uri
             * @description The 800px derivative, used as the plain `src`.
             */
            src: string;
            /** @description Derivative URL keyed by rendered width in pixels. */
            srcset: {
                [key: string]: string;
            };
        };
        /**
         * @description * `uz` - O'zbekcha
         *     * `ru` - Русский
         *     * `en` - English
         * @enum {string}
         */
        LanguageEnum: "uz" | "ru" | "en";
        /** @description The whole menu aggregate returned by `GET /menu/`. */
        Menu: {
            categories: components["schemas"]["MenuCategory"][];
            /** Format: date-time */
            generated_at: string;
        };
        /**
         * @description A top-level section with its subsections and every product beneath it.
         *
         *     Children and products come from lookup tables in the context rather than from the
         *     instance's related managers: the aggregate has already loaded both in bulk, and
         *     touching `category.products` here would reintroduce a query per section.
         */
        MenuCategory: {
            slug: string;
            readonly name: string;
            readonly is_fallback: boolean;
            readonly children: components["schemas"]["Subcategory"][];
            readonly products: components["schemas"]["PublicProduct"][];
        };
        PaginatedAdminCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminCategory"][];
        };
        PaginatedAdminProductList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminProduct"][];
        };
        PaginatedAdminTableList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AdminTable"][];
        };
        PaginatedPublicProductList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PublicProduct"][];
        };
        /** @description A section or subsection with all of its names. */
        PatchedAdminCategoryRequest: {
            parent?: number | null;
            slug?: string;
            order?: number;
            is_active?: boolean;
            translations?: components["schemas"]["CategoryTranslationRequest"][];
        };
        /** @description Full product record: every translation, the gaps, and the stored photos. */
        PatchedAdminProductRequest: {
            category?: number;
            slug?: string;
            /** @description Price in UZS, whole units only. */
            price?: number;
            is_available?: boolean;
            order?: number;
            translations?: components["schemas"]["ProductTranslationRequest"][];
        };
        /** @description A table as the admin UI edits it, plus the URL its QR code resolves to. */
        PatchedAdminTableRequest: {
            number?: number;
            label?: string;
            is_active?: boolean;
        };
        /** @description One product with every photo, for the product page. */
        ProductDetail: {
            slug: string;
            readonly name: string;
            readonly description: string;
            readonly is_fallback: boolean;
            price: number;
            category_slug: string;
            readonly image: components["schemas"]["Image"] | null;
            readonly images: components["schemas"]["Image"][];
        };
        /** @description Multipart upload; the model turns the original into three WebP widths. */
        ProductImageUpload: {
            readonly id: number;
            alt?: string;
            order?: number;
            is_primary?: boolean;
            readonly width: number;
            readonly height: number;
        };
        /** @description Multipart upload; the model turns the original into three WebP widths. */
        ProductImageUploadRequest: {
            /** Format: binary */
            image: string;
            alt?: string;
            order?: number;
            is_primary?: boolean;
        };
        ProductTranslation: {
            language: components["schemas"]["LanguageEnum"];
            name: string;
            description?: string;
        };
        ProductTranslationRequest: {
            language: components["schemas"]["LanguageEnum"];
            name: string;
            description?: string;
        };
        /** @description A product as the storefront reads it, in one language with Uzbek fallback. */
        PublicProduct: {
            slug: string;
            readonly name: string;
            readonly description: string;
            readonly is_fallback: boolean;
            price: number;
            category_slug: string;
            readonly image: components["schemas"]["Image"] | null;
        };
        /**
         * @description * `ADMIN` - Administrator
         *     * `STAFF` - Staff
         * @enum {string}
         */
        RoleEnum: "ADMIN" | "STAFF";
        /** @description Dashboard counters for the admin home screen. */
        Stats: {
            product_count: number;
            available_product_count: number;
            category_count: number;
            /** @description Products lacking at least one of the three languages. */
            missing_translation_count: number;
            scans_last_7_days: number;
        };
        /** @description A second-level category: a label only, its products hang off the section. */
        Subcategory: {
            slug: string;
            readonly name: string;
            readonly is_fallback: boolean;
        };
        /**
         * @description Optional context a scanning client may report about itself.
         *
         *     The field is named `language` rather than after the `locale` column so it shares one
         *     enum with the rest of the schema instead of minting a near-duplicate.
         */
        TableScanRequestRequest: {
            language?: components["schemas"]["LanguageEnum"];
        };
        /** @description All a guest's device needs: which table it just claimed. */
        TableScanResponse: {
            table_number: number;
        };
        /** @description Username/password exchange for an access + refresh pair. */
        TokenObtainPairRequest: {
            username: string;
            password: string;
        };
        /** @description Response body of `POST /auth/token/` (documentation only). */
        TokenPairResponse: {
            access: string;
            refresh: string;
        };
        /** @description Refresh exchange. Rotation is on, so the response carries a new refresh too. */
        TokenRefreshRequest: {
            refresh: string;
        };
        /** @description Response body of `POST /auth/token/refresh/` (documentation only). */
        TokenRefreshResponse: {
            access: string;
            /** @description Rotated refresh token; the previous one is blacklisted. */
            refresh: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    admin_categories_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminCategoryList"];
                };
            };
        };
    };
    admin_categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCategoryRequest"];
                "multipart/form-data": components["schemas"]["AdminCategoryRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCategory"];
                };
            };
        };
    };
    admin_categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Products reference it. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    admin_categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Products reference it. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    admin_categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminCategoryRequest"];
                "multipart/form-data": components["schemas"]["PatchedAdminCategoryRequest"];
            };
        };
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Products reference it. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    admin_products_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminProductList"];
                };
            };
        };
    };
    admin_products_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminProductRequest"];
                "multipart/form-data": components["schemas"]["AdminProductRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProduct"];
                };
            };
        };
    };
    admin_products_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProduct"];
                };
            };
        };
    };
    admin_products_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_products_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminProductRequest"];
                "multipart/form-data": components["schemas"]["PatchedAdminProductRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProduct"];
                };
            };
        };
    };
    admin_products_images_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ProductImageUploadRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImageUpload"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    admin_products_images_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: number;
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    admin_tables_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminTableList"];
                };
            };
        };
    };
    admin_tables_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminTableRequest"];
                "multipart/form-data": components["schemas"]["AdminTableRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTable"];
                };
            };
        };
    };
    admin_tables_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTable"];
                };
            };
        };
    };
    admin_tables_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_tables_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAdminTableRequest"];
                "multipart/form-data": components["schemas"]["PatchedAdminTableRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTable"];
                };
            };
        };
    };
    "admin_tables_qr.svg_retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SVG document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/svg+xml": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "admin_tables_qr_sheet.pdf_retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A4 PDF sheet. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["TokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefreshResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    menu_retrieve: {
        parameters: {
            query?: {
                /** @description Language of the returned strings. Falls back to Uzbek per field. */
                lang?: "en" | "ru" | "uz";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Menu"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    products_list: {
        parameters: {
            query?: {
                /** @description Category slug; a section slug also matches its subsections. */
                category?: string;
                /** @description Language of the returned strings. Falls back to Uzbek per field. */
                lang?: "en" | "ru" | "uz";
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description Case- and accent-insensitive match on the name or description. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPublicProductList"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    products_retrieve: {
        parameters: {
            query?: {
                /** @description Language of the returned strings. Falls back to Uzbek per field. */
                lang?: "en" | "ru" | "uz";
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    tables_scan_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TableScanRequestRequest"];
                "multipart/form-data": components["schemas"]["TableScanRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableScanResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
