// AUTO-GENERATED by scripts/generate-message-catalog.mjs — do not edit by hand.
// Run `npm run gen:messages` after adding or removing a file in messages/.
import enAdmin from '../../messages/en/admin.json';
import enCommon from '../../messages/en/common.json';
import enMenu from '../../messages/en/menu.json';
import enTables from '../../messages/en/tables.json';
import ruAdmin from '../../messages/ru/admin.json';
import ruCommon from '../../messages/ru/common.json';
import ruMenu from '../../messages/ru/menu.json';
import ruTables from '../../messages/ru/tables.json';
import uzAdmin from '../../messages/uz/admin.json';
import uzCommon from '../../messages/uz/common.json';
import uzMenu from '../../messages/uz/menu.json';
import uzTables from '../../messages/uz/tables.json';

/**
 * Every namespace of every locale, keyed by `messages/<locale>/<namespace>.json`.
 * Static imports only, so this module is safe in the edge runtime.
 */
export const messageCatalog = {
  uz: {
    "admin": uzAdmin,
    "common": uzCommon,
    "menu": uzMenu,
    "tables": uzTables
  },
  ru: {
    "admin": ruAdmin,
    "common": ruCommon,
    "menu": ruMenu,
    "tables": ruTables
  },
  en: {
    "admin": enAdmin,
    "common": enCommon,
    "menu": enMenu,
    "tables": enTables
  }
} as const;

export type MessageCatalog = typeof messageCatalog;
